### ISSUE TITLE
Add HCB Mapped Slide

### ISSUE THREAD

**Issue by sampoder** [hackclub/hcb-wrapped-2023#10]
### Slide name

HCBSpendingByLocation

### Slide information

Map all of HCB's `spendingByLocation`, which can be found at `data.hcb.spendingByLocation`. Let's use a heatmap or something.

### Code of Conduct

- [X] I agree to follow Hack Club's Code of Conduct

**Comment by garyhtou** [comment]
Was this handled by the map image added in https://github.com/hackclub/hcb-wrapped-2023/commit/e952a0f27182abb04c2de6190015aad25e5adc3f?

![](https://cloud-q1u33t4vk-hack-club-bot.vercel.app/0amount.png)

**Comment by sampoder** [comment]
Yes!
