### ISSUE TITLE
Add Words Slide

### ISSUE THREAD

**Issue by sampoder** [hackclub/hcb-wrapped-2023#13]
### Slide name

Words

### Slide information

`data.individual.words` has an array of words that each user uses commonly in their memos. Let's make a word cloud! 

Here's a good example of how to do this: https://github.com/hackclub/hcb-wrapped-2022/blob/6e9a8fe4a646acc264981f40a5e125aa74f7a7f2/wrapped.js#L127

### Code of Conduct

- [X] I agree to follow Hack Club's Code of Conduct

**Comment by Aquoria** [comment]
Could I get this issue to try and work on?

**Comment by garyhtou** [comment]
Hey @Aquoria!! Yes!
