### ISSUE TITLE
Title Invisible

### ISSUE THREAD

**Issue by Aquoria** [hackclub/hcb-wrapped-2023#15]
The title `.<span {...$({ color: $.red })}>Hello</span>, World!` is the same color as the background `HelloWorld.config = {
    bg: $.red
} satisfies SlideOptions;` and cannot be seen.
![SS 2023-12-05 at 12 58 37 PM](https://github.com/hackclub/hcb-wrapped-2023/assets/134425658/f10bd546-2ad6-4508-a3a1-e314448569a5)

**Comment by Aquoria** [comment]
Unless I am missing something and this is a non-issue, I can fix this.

**Comment by YodaLightsabr** [comment]
It might also be worth noting that slides don't have to all be red... we'd like to encourage some more variety and vibrancy in slide backgrounds, so we're definitely open to other ideas!

**Comment by Aquoria** [comment]
For this I simply updated the title color so it was visible and kept the background color primary. For my WordCloud slide, it will need a bunch of colors so I made the bg white but the title is:
![SS 2023-12-05 at 3 48 57 PM](https://github.com/hackclub/hcb-wrapped-2023/assets/134425658/b8484e04-d82d-4f9c-af21-34fc4893675a)

**Comment by Aquoria** [comment]
in taking that screenshot I realized the thing I thought I saw earlier had in fact happened.. it seems like some times that bar along the top just decides to keep stretching when on the last slide. Should I open another issue?

**Comment by garyhtou** [comment]
yes! that looks like a bug 🐛 thanks :)
