### ISSUE TITLE
Progress bar going too far

### ISSUE THREAD

**Issue by Aquoria** [hackclub/hcb-wrapped-2023#18]
Sometimes the progress bar at the top keeps going past its end on last slide only. Haven't tracked down a reason or what I'm doing but it seems to maybe be related to switching windows, tabs, or something like that.

![image](https://github.com/hackclub/hcb-wrapped-2023/assets/134425658/b4b831cf-43bf-40e6-9c16-22dd5f830d87)

**Comment by YodaLightsabr** [comment]
I haven't found a way to reproduce it, but if you're able to get me a video or something, let me know!
For now I'll close the issue.
