### ISSUE TITLE
HCB Stat: Shrink font if overflow

### ISSUE THREAD

**Issue by garyhtou** [hackclub/hcb-wrapped-2023#29]
<img width="533" alt="image" src="https://github.com/hackclub/hcb-wrapped-2023/assets/20099646/b5248836-b55a-4736-b0f2-0c1717e7977e">

**Comment by sampoder** [comment]
What user was this? I think this has been fixed (thanks @sarthaktexas!) but I want to test real quick.

**Comment by garyhtou** [comment]
This was christina's it appears to still be an issue

**Comment by garyhtou** [comment]
perfect ty!
<img width="448" alt="image" src="https://github.com/hackclub/hcb-wrapped-2023/assets/20099646/0954dd63-d992-4c38-9d0c-3f9510dac555">
