### ISSUE TITLE
Organization general statistics slide

### ISSUE THREAD

**Issue by YodaLightsabr** [hackclub/hcb-wrapped-2023#3]
This slide will have general statistics about an organization on HCB. For example, the total amount raised or spent as well as the date with the most spending would be good metrics for this slide.

Some useful parts of the `data` object include:
- `organizations[org].category`
- `organizations[org].raised`
- `organizations[org].spent`
- `organizations[org].spendingByDate`
- `organizations[org].spendingByUser`

If you'd like to take this on, self-assign this issue!
![GitHub assign yourself button](https://cloud-ais9nqm7o-hack-club-bot.vercel.app/0image.png)

**Comment by sampoder** [comment]
Implemented last night!
