### ISSUE TITLE
Spender slide: Count up causes layout shift

### ISSUE THREAD

**Issue by garyhtou** [hackclub/hcb-wrapped-2023#30]
https://github.com/hackclub/hcb-wrapped-2023/assets/20099646/14424e27-5003-43ec-8c24-fbe81d02467a

**Comment by sampoder** [comment]
Good catch; which user is this? I'll fix it real quick.

**Comment by garyhtou** [comment]
It was with Daisy's data; although I think I might have seen it with my data too

**Comment by sampoder** [comment]
Cool, let me get this fixed then

**Comment by sampoder** [comment]
Fixed!
