### ISSUE TITLE
Switch out ending slide background

### ISSUE THREAD

**Issue by garyhtou** [hackclub/hcb-wrapped-2023#32]
We love robotics, but it likely doesn't apply to everyone.

![image](https://github.com/hackclub/hcb-wrapped-2023/assets/20099646/810e39b8-009b-4ed8-b194-bf5ed87dada3)

If we wanna, we can keep the robotics background if the user is in an organization categorized as "robotics team". we should still have a generic background this fits everyone

**Comment by sampoder** [comment]
I wonder if we could keep the image but add some context in a caption or something; the intention here was to show how FIRST / robotics was an important area for us this year

**Comment by garyhtou** [comment]
If we want to highlight FIRST/robotics, i think we should have a separate slide for that. This would fall under the category of slides that highlight cool things that happen on HCB. For example, robotics, climate orgs, or orgs that raised the most money (with their permission)

**Comment by sampoder** [comment]
👍 Cool. Any ideas for alternative images?
