### ISSUE TITLE
Add A Platinum Card Slide

### ISSUE THREAD

**Issue by sampoder** [hackclub/hcb-wrapped-2023#8]
### Slide name

PlatinumCard

### Slide information

This April we ran an April Fools prank where a bunch of HCB users received "platinum cards". For those who did (`data.individual.platinumCard` won't be null), it'd be nice to remind them of this. `data.individual.platinumCard` has the card's last four digits and it's associated organisation name. If you'd like to use styling from the main HCB application, let us know in `#hcb-internals`. 

<img width="543" alt="Screenshot 2023-12-04 at 10 12 02 PM" src="https://github.com/hackclub/hcb-wrapped-2023/assets/39828164/0753e545-af10-481e-8b5c-1be254d48223">

### Code of Conduct

- [X] I agree to follow Hack Club's Code of Conduct

**Comment by alx-alexpark** [comment]
I'l attempt this
